basePath: /
host: localhost:8080
info:
  contact: {}
  description: Go + MongoDB powered internal KB system.
  title: KB API Documentation
  version: "1.0"
paths:
  /ping:
    get:
      description: Returns OK
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Health check
      tags:
      - health
swagger: "2.0"
